version: "3"

networks:
  bintuni:

volumes:
  app_data: {}

services:
  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bintuni

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    volumes:
#      - app_data:/var/www/html/storage/logs
      - ./storage/logs/:/var/log
      - ./config-compose/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - bintuni

  grafana:
    image: grafana/grafana:latest
    container_name: grafa
    volumes:
      - ./config-compose/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3200:3000"
    networks:
      - bintuni

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./config-compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - php
    networks:
      - bintuni

  php:
    image: php:8.1-fpm-alpine
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - bintuni


